# Site settings
title: Heartbits2017
email: cesium@di.uminho.pt
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cesium.github.io/heartbits" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

highlighter: rouge

# Build settings
markdown: kramdown

gems:
- jekyll-assets
